"""Validate LLM-produced filters; never interpret natural-language requests."""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

SCHEMA_PATH = Path(__file__).with_name("query-schema.json")
QUERY_SCHEMA = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
_VALIDATOR = Draft202012Validator(QUERY_SCHEMA)


def validate_filters(value: Any) -> dict[str, Any]:
    """Reject unknown/invalid conditions instead of silently widening a query."""
    error = next(_VALIDATOR.iter_errors(value), None)
    if error:
        path = ".".join(map(str, error.absolute_path)) or "filters"
        raise ValueError(f"{path}: {error.message}")
    result = dict(value)
    for key, item in result.items():
        if isinstance(item, str) and not item.strip():
            raise ValueError(f"{key} cannot be blank")
        if isinstance(item, (int, float)) and not isinstance(item, bool):
            if isinstance(item, float) and not math.isfinite(item):
                raise ValueError(f"{key} must be finite")
            if QUERY_SCHEMA["properties"][key]["type"] == "integer":
                result[key] = int(item)
    for lower, upper in (("min_credits", "max_credits"), ("period_start", "period_end")):
        if lower in result and upper in result and result[lower] > result[upper]:
            raise ValueError(f"{lower} cannot be greater than {upper}")
    result.setdefault("limit", 20)
    result.setdefault("offset", 0)
    return result


def decode_filters(raw: str) -> dict[str, Any]:
    def reject_constant(value: str) -> None:
        raise ValueError(f"Invalid JSON number: {value}")

    def unique_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"Duplicate JSON field: {key}")
            result[key] = value
        return result

    if len(raw) > 10000:
        raise ValueError("filters JSON is too large (maximum 10000 characters)")
    try:
        value = json.loads(raw, parse_constant=reject_constant, object_pairs_hook=unique_keys)
    except json.JSONDecodeError as exc:
        raise ValueError("Expected a JSON filter object generated by your AI tool; see /api/query-schema") from exc
    return validate_filters(value)
